# 两张表A、B，多种写法实现查询ID在A表中，但不在B表中的数据

CREATE TABLE IF NOT EXISTS A(ID INT);
CREATE TABLE IF NOT EXISTS B(ID INT);

# 方法一：仅适用于单个字段，效率较低
SELECT A.ID FROM A WHERE A.ID NOT IN (SELECT ID FROM B);

# 方法二：使用左连接
SELECT A.ID FROM A LEFT JOIN B ON A.ID = B.ID WHERE B.ID IS NULL;

# 方法三
SELECT * FROM B WHERE (SELECT COUNT(1) AS NUM FROM A WHERE A.ID = B.ID) = 0;

# 方法四
SELECT * FROM A WHERE NOT EXISTS(SELECT 1 FROM B WHERE A.ID = B.ID);